version: "3"
services:
  db:
    restart: always
    container_name: db
    command:
      --lower_case_table_names=1
      --character-set-server=utf8mb4
      --collation-server=utf8mb4_general_ci
      --explicit_defaults_for_timestamp=true
    image: mysql:5.7
    environment:
      MYSQL_USER: wyswill
      MYSQL_PASSWORD: wyswill123123
      MYSQL_ROOT_PASSWORD: wyswill123
    ports:
      - 3306:3306