name: CI
on:
  push:
    branches:
      - wyswill_dev
# jobs:
#   automerge:
#     runs-on: ubuntu-latest
#     steps:
#       - name: Action-Automerge
#         uses: mtanzi/action-automerge@v1

# name: Update cms/master

# on:
#   push:
#     branches:
#       - master
jobs:
  update-cms-master:
    name: Merge master into release after a PR is merged
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: merge
        uses: mtanzi/action-automerge@v1
        id: merge
        with:
          github_token: ${{ secrets.AUTO_MERGE  }}
          source: 'master'
          target: 'release'
          webhook_url: #if present add the Slack webhook