name: CI
on:
  push:
    branches:
      - wyswill_dev
jobs:
  update-cms-master:
    name: Merge master into release after a PR is merged
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: merge
        uses: mtanzi/action-automerge@v1
        id: merge
        with:
          github_token: ${{ secrets.AUTO_MERGE  }}
          source: 'wyswill_dev'
          target: 'master'
          webhook_url: #if present add the Slack webhook