name: aruoMerge
on:
  push:
    branches:
      - wyswill_dev
      - master
jobs:
  update-cms-master:
    name: Merge master into release after a PR is merged
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: merge
        uses: mtanzi/action-automerge@v1
        id: merge
        with:
          github_token: '9c75da5dc7d1220f1652e75e43db21930d7d244c'
          source: 'wyswill_dev'
          target: 'master'